### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-loading bundle size difference from 4.0.0 to 25aed7e27f00983ab45c867871b4e8f557814fdd
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-loading bundle size difference from 4.0.0 to 8ed06afe364ca5fbd8e17e00d6c00e30d4f33466
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-loading bundle size difference from 4.0.0 to e4ed0836a1070e986e68f8aff39ddbbcb7ddff03
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-loading bundle size difference from 4.0.0 to da4ca819ef3d5ccb659e6fac78ae392087173dfe
No significant bundle size differences found.

**Pull request merged**
